name: Publish test

on:
  push:
     branches:
       - next
  # push:
  #   tags:
  #     - 'v**'
jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # - name: Checkout branche
      #   run: |
      #     git checkout next
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Sync to taobao 
        run: |
          yarn syncToTaoBao
